import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { Card } from '../components/ui/card';
import { Shield, Lock, Eye, Database, UserCheck, Bell, FileText, AlertTriangle, Heart, Users } from 'lucide-react';

interface PrivacyPolicyPageProps {
  language: 'bn' | 'en';
  setLanguage: (lang: 'bn' | 'en') => void;
  setPage: (page: string) => void;
  announcement?: { title: string; message: string; type: string } | null;
  onLogin?: (type: 'teacher' | 'guardian' | 'student' | 'admin' | 'donor', userData?: any) => void;
}

const content = {
  bn: {
    pageTitle: 'গোপনীয়তা নীতি',
    subtitle: 'আপনার গোপনীয়তা আমাদের অগ্রাধিকার',
    description: 'Talent Tutor কীভাবে আপনার ব্যক্তিগত তথ্য সংগ্রহ, ব্যবহার এবং সুরক্ষিত রাখে তা জানুন',
    lastUpdated: 'সর্বশেষ আপডেট: ০৪ নভেম্বর ২০২৫',
    introText: `Talent Tutor ("আমরা", "আমাদের", বা "আমাদেরকে") এ আপনার গোপনীয়তা রক্ষা করতে প্রতিশ্রুতিবদ্ধ। এই গোপনীয়তা নীতি ব্যাখ্যা করে যে আমরা কীভাবে আপনার ব্যক্তিগত তথ্য সংগ্রহ, ব্যবহার, শেয়ার এবং সুরক্ষিত রাখি যখন আপনি আমাদের টিউশন মার্কেটপ্লেস প্ল্যাটফর্ম ব্যবহার করেন। এই প্ল্যাটফর্মে ৬ ধরনের ব্যবহারকারী রয়েছে এবং যাকাত/দান ব্যবস্থা অন্তর্ভুক্ত। আমাদের সেবা ব্যবহার করে, আপনি এই নীতিতে বর্ণিত অনুশীলনে সম্মত হন।`,
    contactTitle: 'প্রশ্ন বা উদ্বেগ?',
    contactText: 'গোপনীয়তা সম্পর্কিত যেকোনো প্রশ্ন বা উদ্বেগের জন্য আমাদের সাথে যোগাযোগ করুন',
    contactEmail: 'ইমেইল: privacy@talenttutor.com',
    contactSupport: 'সাপোর্ট: support@talenttutor.com',
    contactPhone: 'ফোন: +৮৮০ ১৫৮১-৮৫৫২৩৮',
    contactHotline: 'হটলাইন: +৮৮০ ১৮০০-১১১১১১',
    contactAddress: 'ঠিকানা: ঢাকা, বাংলাদেশ',
  },
  en: {
    pageTitle: 'Privacy Policy',
    subtitle: 'Your Privacy is Our Priority',
    description: 'Learn how Talent Tutor collects, uses, and protects your personal information',
    lastUpdated: 'Last Updated: November 4, 2025',
    introText: `At Talent Tutor ("we", "our", or "us"), we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, share, and protect your personal information when you use our tuition marketplace platform. This platform has 6 types of users and includes a Zakat/donation system. By using our services, you agree to the practices described in this policy.`,
    contactTitle: 'Questions or Concerns?',
    contactText: 'Contact us for any questions or concerns regarding privacy',
    contactEmail: 'Email: privacy@talenttutor.com',
    contactSupport: 'Support: support@talenttutor.com',
    contactPhone: 'Phone: +880 1581-855238',
    contactHotline: 'Hotline: +880 1800-111111',
    contactAddress: 'Address: Dhaka, Bangladesh',
  }
};

export function PrivacyPolicyPage({ language, setLanguage, setPage, announcement, onLogin }: PrivacyPolicyPageProps) {
  const t = content[language];
  
  const sections = language === 'bn' ? [
    {
      icon: Database,
      title: 'তথ্য সংগ্রহ',
      content: [
        'আমরা নিম্নলিখিত তথ্য সংগ্রহ করি:',
        '',
        'ব্যক্তিগত তথ্য:',
        '• নাম, ইমেইল ঠিকানা, ফোন নম্বর',
        '• ঠিকানা (এলাকা, জেলা, বিভাগ)',
        '• জন্ম তারিখ এবং জেন্ডার',
        '',
        'যাচাইকরণ তথ্য:',
        '• জাতীয় পরিচয়পত্র (NID) নম্বর',
        '• শিক্ষাগত সনদপত্র ও যোগ্যতা',
        '• প্রোফাইল ছবি এবং শিক্ষামূলক নথিপত্র',
        '',
        'পেমেন্ট তথ্য:',
        '• ক্রেডিট লেনদেনের বিবরণ',
        '• বিকাশ/নগদ/SSL পেমেন্ট তথ্য',
        '• যাকাত/দান লেনদেনের রেকর্ড',
        '• কার্ড নম্বর সংরক্ষণ করা হয় না (পেমেন্ট গেটওয়ে সরাসরি প্রক্রিয়া করে)',
        '',
        'ব্যবহার তথ্য:',
        '• লগইন সময়, IP ঠিকানা, ব্রাউজার টাইপ',
        '• ডিভাইস তথ্য (মোবাইল/ডেস্কটপ)',
        '• প্ল্যাটফর্ম ব্যবহারের প্যাটার্ন',
        '',
        'প্রোফাইল তথ্য:',
        '• দক্ষতা, অভিজ্ঞতা, বিষয় পছন্দ',
        '• রিভিউ এবং রেটিং',
        '• টিউশন পোস্ট এবং আবেদন',
        '• ছাত্র/অসহায়দের সাহায্যের আবেদন',
      ],
    },
    {
      icon: Eye,
      title: 'তথ্যের ব্যবহার',
      content: [
        'আমরা আপনার তথ্য নিম্নলিখিত উদ্দেশ্যে ব্যবহার করি:',
        '',
        '১. প্ল্যাটফর্ম পরিচালনা:',
        '• ৬ ধরনের ব্যবহারকারী অ্যাকাউন্ট তৈরি ও রক্ষণাবেক্ষণ (শিক্ষক, অভিভাবক, ছাত্র/অসহায়, অ্যাডমিন, যাকাত প্রদানকারী, শিক্ষা উপকরণ দাতা)',
        '• প্রোফাইল সম্পূর্ণতা যাচাইকরণ',
        '• পরিচয় ও যোগ্যতা যাচাইকরণ',
        '',
        '২. ম্যাচিং ও যোগাযোগ:',
        '• শিক্ষক-অভিভাবক ম্যাচিং',
        '• যোগাযোগের জন্য ক্রেডিট ব্যবস্থাপনা',
        '• ছাত্রদের জন্য শিক্ষক যোগাযোগ সীমাবদ্ধতা প্রয়োগ',
        '',
        '৩. ক্রেডিট ব্যবস্থাপনা:',
        '• নতুন শিক্ষকদের ৫০ ফ্রি ক্রেডিট প্রদান',
        '• নতুন অভিভাবকদের ১০০ ফ্রি ক্রেডিট প্রদান',
        '• ক্রেডিট ব্যবহার এবং ক্রয়ের ট্র্যাকিং',
        '',
        '৪. মানবিক উদ্যোগ:',
        '• ছাত্র/অসহায়দের আবেদন প্রক্রিয়াকরণ',
        '• যাকাত/দান সংগ্রহ ও বিতরণ',
        '• শিক্ষা উপকরণ দাতাদের সাথে সংযোগ',
        '• দানের রসিদ এবং সার্টিফিকেট তৈরি',
        '',
        '৫. নিরাপত্তা ও সহায়তা:',
        '• প্রতারণা প্রতিরোধ এবং নিরাপত্তা নিশ্চিতকরণ',
        '• গ্রাহক সেবা এবং টিকেট সিস্টেম পরিচালনা',
        '• বিরোধ সমাধান',
        '',
        '৬. যোগাযোগ:',
        '• গুরুত্বপূর্ণ আপডেট এবং নোটিফিকেশন',
        '• নিউজলেটার এবং সফলতার গল্প',
        '• নীতিমালা ও গাইডলাইন আপডেট',
      ],
    },
    {
      icon: UserCheck,
      title: 'তথ্য শেয়ারিং',
      content: [
        'আমরা আপনার তথ্য তৃতীয় পক্ষের সাথে বিক্রি বা ভাড়া দিই না। তবে নিম্নলিখিত ক্ষেত্রে শেয়ার করি:',
        '',
        'প্ল্যাটফর্মের মধ্যে শেয়ারিং:',
        '• শিক্ষক এবং অভিভাবকরা পরস্পরের প্রোফাইল দেখতে পারেন',
        '• সবাই প্রোফাইল দেখতে পারে, কিন্তু যোগাযোগের জন্য রেজিস্ট্রেশন, প্রোফাইল সম্পূর্ণতা ও ক্রেডিট প্রয়োজন',
        '• ছাত্ররা শুধু দেখতে পারে, শিক্ষকদের সাথে যোগাযোগ করতে পারে না',
        '• দাতারা ছাত্র/অসহায়দের আবেদন দেখতে পারেন',
        '',
        'সেবা প্রদানকারী:',
        '• পেমেন্ট গেটওয়ে (bKash, Nagad, SSL Commerz)',
        '• SMS ও ইমেইল সেবা প্রদানকারী',
        '• ক্লাউড স্টোরেজ (Supabase)',
        '',
        'আইনি বাধ্যবাধকতা:',
        '• আইন প্রয়োগকারী সংস্থার বৈধ অনুরোধে',
        '• আদালতের আদেশ মেনে চলতে',
        '• জরুরি পরিস্থিতিতে নিরাপত্তা রক্ষায়',
        '',
        'আমরা কখনো:',
        '• বিজ্ঞাপনের জন্য আপনার তথ্য ব্যবহার করি না',
        '• তৃতীয় পক্ষের কাছে তথ্য বিক্রি করি না',
        '• অনুমতি ছাড়া বিপণন উদ্দেশ্যে তথ্য শেয়ার করি না',
      ],
    },
    {
      icon: Lock,
      title: 'তথ্য সুরক্ষা',
      content: [
        'আপনার তথ্য সুরক্ষিত রাখতে আমরা শিল্পমান ব্যবস্থা গ্রহণ করি:',
        '',
        'প্রযুক্তিগত সুরক্ষা:',
        '• SSL/TLS এনক্রিপশন (সব ডেটা ট্রান্সমিশনে)',
        '• নিরাপদ Supabase সার্ভারে ডেটা সংরক্ষণ',
        '• পাসওয়ার্ড হ্যাশিং এবং এনক্রিপশন',
        '• নিয়মিত নিরাপত্তা অডিট ও আপডেট',
        '',
        'অ্যাক্সেস নিয়ন্ত্রণ:',
        '• রোল-বেসড অ্যাক্সেস কন্ট্রোল (৬ ইউজার টাইপ)',
        '• সীমিত কর্মী অ্যাক্সেস',
        '• দুই-ফ্যাক্টর অথেন্টিকেশন (2FA) সুবিধা',
        '• নিয়মিত পাসওয়ার্ড আপডেটের সুপারিশ',
        '',
        'ডেটা ব্যাকআপ:',
        '• দৈনিক স্বয়ংক্রিয় ব্যাকআপ',
        '• মাল্টিপল জিও-রিডান্ডেন্ট স্টোরেজ',
        '• দুর্যোগ পুনরুদ্ধার পরিকল্পনা',
        '',
        'পেমেন্ট নিরাপত্তা:',
        '• PCI DSS সম্মত পেমেন্ট প্রসেসিং',
        '• কার্ড তথ্য সংরক্ষণ করা হয় না',
        '• নিরাপদ পেমেন্ট গেটওয়ে ইন্টিগ্রেশন',
      ],
    },
    {
      icon: FileText,
      title: 'আপনার অধিকার',
      content: [
        'ডেটা সুরক্ষা আইন অনুযায়ী আপনার নিম্নলিখিত অধিকার রয়েছে:',
        '',
        'অ্যাক্সেস ও পোর্টেবিলিটি:',
        '• আপনার সব ব্যক্তিগত ডেটা অ্যাক্সেস করার অধিকার',
        '• আপনার ডেটা ডাউনলোড করার অধিকার (JSON/CSV ফরম্যাটে)',
        '• ডেটা কীভাবে ব্যবহৃত হচ্ছে তা জানার অধিকার',
        '',
        'সংশোধন ও আপডেট:',
        '• ভুল তথ্য সংশোধন করার অধিকার',
        '• আপনার প্রোফাইল যেকোনো সময় আপডেট করার অধিকার',
        '• পুরানো তথ্য মুছে ফেলার অধিকার',
        '',
        'মুছে ফেলা ও সীমাবদ্ধতা:',
        '• আপনার অ্যাকাউন্ট এবং ডেটা মুছে ফেলার অধিকার',
        '• নির্দিষ্ট ডেটা প্রসেসিং সীমিত করার অধিকার',
        '• ডেটা মুছে ফেলার ৩০ দিন পর স্থায়ীভাবে মুছে যাবে',
        '',
        'যোগাযোগ নিয়ন্ত্রণ:',
        '• মার্কেটিং ইমেইল অপ্ট-আউট করার অধিকার',
        '• নোটিফিকেশন সেটিংস কাস্টমাইজ করার অধিকার',
        '• নিউজলেটার সাবস্ক্রিপশন বাতিল করার অধিকার',
        '',
        'আপত্তি ও অভিযোগ:',
        '• নির্দিষ্ট ডেটা প্রসেসিংয়ে আপত্তি করার অধিকার',
        '• ডেটা সুরক্ষা কর্তৃপক্ষের কাছে অভিযোগ করার অধিকার',
        '',
        'এই অধিকারগুলি ব্যবহার করতে:',
        '• ইমেইল: privacy@talenttutor.com',
        '• ফোন: +৮৮০ ১৫৮১-৮৫৫২৩৮',
        '• ড্যাশবোর্ড সেটিংস থেকেও অনেক নিয়ন্ত্রণ পাওয়া যায়',
      ],
    },
    {
      icon: Bell,
      title: 'কুকিজ এবং ট্র্যাকিং',
      content: [
        'আমরা আপনার অভিজ্ঞতা উন্নত করতে কুকিজ ব্যবহার করি:',
        '',
        'অপরিহার্য কুকিজ (Essential):',
        '• লগইন সেশন বজায় রাখা',
        '• নিরাপত্তা ও প্রমাণীকরণ',
        '• ভাষা পছন্দ মনে রাখা',
        '• এগুলো প্ল্যাটফর্ম কাজ করার জন্য আবশ্যক',
        '',
        'কার্যকরী কুকিজ (Functional):',
        '• ক্রেডিট ব্যালেন্স ট্র্যাকিং',
        '• ড্যাশবোর্ড পছন্দ সংরক্ষণ',
        '• চ্যাট সেশন বজায় রাখা',
        '',
        'বিশ্লেষণ কুকিজ (Analytics):',
        '• প্ল্যাটফর্ম ব্যবহার বিশ্লেষণ',
        '• জনপ্রিয় ফিচার চিহ্নিতকরণ',
        '• ইউজার এক্সপেরিয়েন্স উন্নতি',
        '',
        'পছন্দ কুকিজ (Preference):',
        '• থিম সেটিংস (লাইট/ডার্ক)',
        '• বিজ্ঞপ্তি পছন্দ',
        '• ড্যাশবোর্ড লেআউট',
        '',
        'কুকিজ নিয়ন্ত্রণ:',
        '• ব্রাউজার সেটিংস থেকে কুকিজ নিয়ন্ত্রণ করুন',
        '• অপরিহার্য কুকিজ ছাড়া অন্যগুলো অক্ষম করতে পারেন',
        '• কুকিজ মুছে ফেলতে পারেন তবে কিছু ফিচার কাজ নাও করতে পারে',
      ],
    },
    {
      icon: AlertTriangle,
      title: 'শিশু ও ছাত্রদের গোপনীয়তা',
      content: [
        'আমরা শিশু ও ছাত্রদের গোপনীয়তা বিশেষভাবে রক্ষা করি:',
        '',
        'বয়স সীমাবদ্ধতা:',
        '• ১৮ বছরের কম বয়সীদের অভিভাবকের সম্মতি প্রয়োজন',
        '• ১৩ বছরের কম বয়সীদের থেকে জেনেশুনে তথ্য সংগ্রহ করি না',
        '• অভিভাবক ছাড়া শিশুরা স্বাধীনভাবে রেজিস্ট্রেশন করতে পারে না',
        '',
        'ছাত্র/অসহায় অ্যাকাউন্ট:',
        '• ছাত্ররা শুধু সাহায্যের আবেদন করতে পারে',
        '• তারা শিক্ষকদের সাথে সরাসরি যোগাযোগ করতে পারে না',
        '• আবেদন যাচাইকরণের পর দাতাদের সাথে সংযোগ হয়',
        '• ব্যক্তিগত তথ্য সীমিতভাবে প্রদর্শিত হয়',
        '',
        'অভিভাবকের নিয়ন্ত্রণ:',
        '• অভিভাবকরা তাদের সন্তানের প্রোফাইল পরিচালনা করতে পারেন',
        '• সন্তানের সব যোগাযোগ মনিটর করতে পারেন',
        '• যেকোনো সময় অ্যাকাউন্ট মুছে ফেলতে পারেন',
        '',
        'ডেটা ন্যূনতমকরণ:',
        '• শুধু প্রয়োজনীয় তথ্য সংগ্রহ করা হয়',
        '• সংবেদনশীল তথ্য অতিরিক্ত সুরক্ষিত',
        '• পাবলিক প্রোফাইলে ব্যক্তিগত তথ্য সীমিত',
      ],
    },
    {
      icon: Heart,
      title: 'যাকাত/দান সংক্রান্ত গোপনীয়তা',
      content: [
        'মানবিক উদ্যোগে বিশেষ গোপনীয়তা নীতি:',
        '',
        'দাতাদের তথ্য:',
        '• দাতাদের পরিচয় গোপন রাখা যায় (ঐচ্ছিক)',
        '• দানের পরিমাণ ও রসিদ নিরাপদে সংরক্ষিত',
        '• ট্যাক্স রিটার্নের জন্য সার্টিফিকেট প্রদান',
        '• দাতারা তাদের দানের ইতিহাস দেখতে পারেন',
        '',
        'গ্রহীতাদের তথ্য (ছাত্র/অসহায়):',
        '• আবেদনে যাচাইকৃত প্রয়োজন তথ্য',
        '• ব্যক্তিগত তথ্য শুধু যাচাইকারী ও অনুমোদিত দাতারা দেখতে পারেন',
        '• গ্রহীতাদের সম্মান ও গোপনীয়তা রক্ষা করা হয়',
        '• সফলতার গল্পে নাম প্রকাশ ঐচ্ছিক',
        '',
        'শিক্ষা উপকরণ দাতা:',
        '• দানকৃত বই/উপকরণের তালিকা',
        '• প্রাপকদের সাথে সংযোগের তথ্য',
        '• বিতরণ ট্র্যাকিং',
        '',
        'স্বচ্ছতা:',
        '• দানের ব্যবহার ট্র্যাক করা যায়',
        '• মাসিক প্রভাব রিপোর্ট পাওয়া যায়',
        '• সব লেনদেন নিরীক্ষিত',
      ],
    },
    {
      icon: Users,
      title: 'ব্যবহারকারী টাইপ অনুযায়ী গোপনীয়তা',
      content: [
        'প্রতিটি ব্যবহারকারী টাইপের জন্য নির্দিষ্ট গোপনীয়তা নীতি:',
        '',
        '১. শিক্ষক:',
        '• শিক্ষাগত যোগ্যতা ও NID যাচাইকৃত',
        '• প্রোফাইল পাবলিকলি দৃশ্যমান',
        '• ৫০ ফ্রি ক্রেডিট তথ্য ট্র্যাক করা হয়',
        '• রিভিউ ও রেটিং প্রদর্শিত',
        '',
        '২. অভিভাবক:',
        '• প্রোফাইল আংশিকভাবে দৃশ্যমান',
        '• পোস্ট করা টিউশন পাবলিক',
        '• ১০০ ফ্রি ক্রেডিট ম্যানেজমেন্ট',
        '• যোগাযোগ ইতিহাস সংরক্ষিত',
        '',
        '৩. ছাত্র/অসহায়:',
        '• শুধু সাহায্যের আবেদন প্রদর্শিত',
        '• ব্যক্তিগত তথ্য গোপন রাখা হয়',
        '• যাচাইকরণের পর প্রয়োজনীয় তথ্য শেয়ার',
        '• শিক্ষক যোগাযোগ নিষিদ্ধ',
        '',
        '৪. অ্যাডমিন:',
        '• সীমিত ডেটা অ্যাক্সেস (প্রয়োজন অনুযায়ী)',
        '• সব অ্যাক্সেস লগ করা হয়',
        '• গোপনীয়তা চুক্তিতে আবদ্ধ',
        '',
        '৫. যাকাত প্রদানকারী:',
        '• দানের তথ্য ব্যক্তিগত',
        '• রসিদ ও সার্টিফিকেট নিরাপদ',
        '• গ্রহীতাদের সাথে সীমিত তথ্য শেয়ার',
        '',
        '৬. শিক্ষা উপকরণ দাতা:',
        '• দানকৃত উপকরণ তালিকা',
        '• প্রাপকদের সাথে শেয়ারিং পছন্দ',
        '• বিতরণ তথ্য ট্র্যাক',
      ],
    },
    {
      icon: FileText,
      title: 'পলিসি পরিবর্তন ও আপডেট',
      content: [
        'গোপনীয়তা নীতি আপডেট সম্পর্কে:',
        '',
        'পরিবর্তন প্রক্রিয়া:',
        '• আমরা এই গোপনীয়তা নীতি সময়ে সময়ে আপডেট করতে পারি',
        '• ছোট পরিবর্তনের জন্য ওয়েবসাইটে নোটিশ',
        '• বড় পরিবর্তনের জন্য ইমেইল/নোটিফিকেশন',
        '• ৩০ দিনের নোটিশ (গুরুত্বপূর্ণ পরিবর্তনে)',
        '',
        'আপনার দায়িত্ব:',
        '• নিয়মিত গোপনীয়তা নীতি পরীক্ষা করুন',
        '• আপডেটের পর অব্যাহত ব্যবহার = স্বীকৃতি',
        '• অসম্মতি থাকলে অ্যাকাউন্ট বন্ধ করতে পারেন',
        '',
        'সংস্করণ ইতিহাস:',
        '• প্রতিটি সংস্করণ তারিখ সহ সংরক্ষিত',
        '• পুরানো সংস্করণ অনুরোধে পাওয়া যায়',
        '• পরিবর্তনের লগ রক্ষণাবেক্ষণ করা হয়',
        '',
        'বর্তমান সংস্করণ:',
        '• সর্বশেষ আপডেট: ০৪ নভেম্বর ২০২৫',
        '• কার্যকর তারিখ: ০৪ নভেম্বর ২০২৫',
        '• সংস্করণ: 2.0',
        '',
        'পরবর্তী পর্যালোচনা: জানুয়ারি ২০২৬',
      ],
    },
  ] : [
    {
      icon: Database,
      title: 'Information Collection',
      content: [
        'We collect the following information:',
        '',
        'Personal Information:',
        '• Name, email address, phone number',
        '• Address (area, district, division)',
        '• Date of birth and gender',
        '',
        'Verification Information:',
        '• National ID (NID) number',
        '• Educational certificates and qualifications',
        '• Profile photo and educational documents',
        '',
        'Payment Information:',
        '• Credit transaction details',
        '• bKash/Nagad/SSL payment information',
        '• Zakat/donation transaction records',
        '• Card numbers are not stored (processed directly by payment gateway)',
        '',
        'Usage Information:',
        '• Login time, IP address, browser type',
        '• Device information (mobile/desktop)',
        '• Platform usage patterns',
        '',
        'Profile Information:',
        '• Skills, experience, subject preferences',
        '• Reviews and ratings',
        '• Tuition posts and applications',
        '• Student/helpless assistance applications',
      ],
    },
    {
      icon: Eye,
      title: 'Information Usage',
      content: [
        'We use your information for the following purposes:',
        '',
        '1. Platform Operation:',
        '• Create and maintain 6 types of user accounts (Teacher, Guardian, Student/Helpless, Admin, Zakat Donor, Education Material Donor)',
        '• Profile completion verification',
        '• Identity and qualification verification',
        '',
        '2. Matching & Communication:',
        '• Teacher-guardian matching',
        '• Credit management for communication',
        '• Enforce student-teacher contact restrictions',
        '',
        '3. Credit Management:',
        '• Provide 50 free credits to new teachers',
        '• Provide 100 free credits to new guardians',
        '• Track credit usage and purchases',
        '',
        '4. Humanitarian Initiatives:',
        '• Process student/helpless applications',
        '• Collect and distribute Zakat/donations',
        '• Connect with education material donors',
        '• Generate donation receipts and certificates',
        '',
        '5. Security & Support:',
        '• Fraud prevention and security',
        '• Customer service and ticket system',
        '• Dispute resolution',
        '',
        '6. Communication:',
        '• Important updates and notifications',
        '• Newsletters and success stories',
        '• Policy and guideline updates',
      ],
    },
    {
      icon: UserCheck,
      title: 'Information Sharing',
      content: [
        'We do not sell or rent your information to third parties. However, we share in the following cases:',
        '',
        'Within Platform:',
        '• Teachers and guardians can view each other\'s profiles',
        '• Everyone can view profiles, but registration, profile completion & credits required for contact',
        '• Students can only view, cannot contact teachers',
        '• Donors can see student/helpless applications',
        '',
        'Service Providers:',
        '• Payment gateways (bKash, Nagad, SSL Commerz)',
        '• SMS and email service providers',
        '• Cloud storage (Supabase)',
        '',
        'Legal Obligations:',
        '• Valid requests from law enforcement',
        '• Court orders',
        '• Emergency situations for safety',
        '',
        'We never:',
        '• Use your information for advertising',
        '• Sell information to third parties',
        '• Share information for marketing without permission',
      ],
    },
    {
      icon: Lock,
      title: 'Information Security',
      content: [
        'We take industry-standard measures to protect your information:',
        '',
        'Technical Security:',
        '• SSL/TLS encryption (all data transmissions)',
        '• Secure Supabase server storage',
        '• Password hashing and encryption',
        '• Regular security audits and updates',
        '',
        'Access Control:',
        '• Role-based access control (6 user types)',
        '• Limited staff access',
        '• Two-factor authentication (2FA) available',
        '• Regular password update recommendations',
        '',
        'Data Backup:',
        '• Daily automatic backups',
        '• Multiple geo-redundant storage',
        '• Disaster recovery plan',
        '',
        'Payment Security:',
        '• PCI DSS compliant payment processing',
        '• Card information not stored',
        '• Secure payment gateway integration',
      ],
    },
    {
      icon: FileText,
      title: 'Your Rights',
      content: [
        'According to data protection laws, you have the following rights:',
        '',
        'Access & Portability:',
        '• Right to access all your personal data',
        '• Right to download your data (JSON/CSV format)',
        '• Right to know how data is being used',
        '',
        'Correction & Update:',
        '• Right to correct incorrect information',
        '• Right to update your profile anytime',
        '• Right to delete old information',
        '',
        'Deletion & Restriction:',
        '• Right to delete your account and data',
        '• Right to restrict certain data processing',
        '• Data permanently deleted 30 days after deletion',
        '',
        'Communication Control:',
        '• Right to opt-out of marketing emails',
        '• Right to customize notification settings',
        '• Right to cancel newsletter subscription',
        '',
        'Objection & Complaint:',
        '• Right to object to specific data processing',
        '• Right to complain to data protection authority',
        '',
        'To exercise these rights:',
        '• Email: privacy@talenttutor.com',
        '• Phone: +880 1581-855238',
        '• Many controls available from dashboard settings',
      ],
    },
    {
      icon: Bell,
      title: 'Cookies and Tracking',
      content: [
        'We use cookies to improve your experience:',
        '',
        'Essential Cookies:',
        '• Maintain login sessions',
        '• Security and authentication',
        '• Remember language preference',
        '• Required for platform functionality',
        '',
        'Functional Cookies:',
        '• Track credit balance',
        '• Save dashboard preferences',
        '• Maintain chat sessions',
        '',
        'Analytics Cookies:',
        '• Analyze platform usage',
        '• Identify popular features',
        '• Improve user experience',
        '',
        'Preference Cookies:',
        '• Theme settings (light/dark)',
        '• Notification preferences',
        '• Dashboard layout',
        '',
        'Cookie Control:',
        '• Control cookies from browser settings',
        '• Can disable non-essential cookies',
        '• Can delete cookies but some features may not work',
      ],
    },
    {
      icon: AlertTriangle,
      title: 'Children & Student Privacy',
      content: [
        'We specially protect children and student privacy:',
        '',
        'Age Restrictions:',
        '• Parental consent required for under 18',
        '• Do not knowingly collect information from under 13',
        '• Children cannot register independently without guardian',
        '',
        'Student/Helpless Accounts:',
        '• Students can only apply for assistance',
        '• Cannot directly contact teachers',
        '• Connected with donors after application approval',
        '• Personal information shown limitedly',
        '',
        'Parental Control:',
        '• Parents can manage their child\'s profile',
        '• Can monitor all child communication',
        '• Can delete account anytime',
        '',
        'Data Minimization:',
        '• Collect only necessary information',
        '• Additional protection for sensitive information',
        '• Limited personal information on public profiles',
      ],
    },
    {
      icon: Heart,
      title: 'Zakat/Donation Privacy',
      content: [
        'Special privacy policy for humanitarian initiatives:',
        '',
        'Donor Information:',
        '• Can keep donor identity private (optional)',
        '• Donation amount and receipts securely stored',
        '• Certificates provided for tax returns',
        '• Donors can view their donation history',
        '',
        'Recipient Information (Student/Helpless):',
        '• Verified need information in application',
        '• Personal info visible only to verifiers and approved donors',
        '• Recipients\' dignity and privacy protected',
        '• Name disclosure in success stories optional',
        '',
        'Education Material Donors:',
        '• List of donated books/materials',
        '• Connection information with recipients',
        '• Distribution tracking',
        '',
        'Transparency:',
        '• Can track donation usage',
        '• Monthly impact reports available',
        '• All transactions audited',
      ],
    },
    {
      icon: Users,
      title: 'Privacy by User Type',
      content: [
        'Specific privacy policies for each user type:',
        '',
        '1. Teacher:',
        '• Educational qualifications & NID verified',
        '• Profile publicly visible',
        '• 50 free credit information tracked',
        '• Reviews and ratings displayed',
        '',
        '2. Guardian:',
        '• Profile partially visible',
        '• Posted tuitions public',
        '• 100 free credit management',
        '• Contact history preserved',
        '',
        '3. Student/Helpless:',
        '• Only assistance applications displayed',
        '• Personal information kept private',
        '• Necessary information shared after verification',
        '• Teacher contact prohibited',
        '',
        '4. Admin:',
        '• Limited data access (as needed)',
        '• All access logged',
        '• Bound by privacy agreement',
        '',
        '5. Zakat Donor:',
        '• Donation information private',
        '• Receipts and certificates secure',
        '• Limited information shared with recipients',
        '',
        '6. Education Material Donor:',
        '• Donated materials list',
        '• Sharing preference with recipients',
        '• Distribution information tracked',
      ],
    },
    {
      icon: FileText,
      title: 'Policy Changes & Updates',
      content: [
        'About privacy policy updates:',
        '',
        'Change Process:',
        '• We may update this privacy policy from time to time',
        '• Website notice for minor changes',
        '• Email/notification for major changes',
        '• 30-day notice (for important changes)',
        '',
        'Your Responsibility:',
        '• Regularly check privacy policy',
        '• Continued use after update = acceptance',
        '• Can close account if disagree',
        '',
        'Version History:',
        '• Each version saved with date',
        '• Old versions available on request',
        '• Change log maintained',
        '',
        'Current Version:',
        '• Last Update: November 4, 2025',
        '• Effective Date: November 4, 2025',
        '• Version: 2.0',
        '',
        'Next Review: January 2026',
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 via-white to-cyan-50">
      <Header language={language} setLanguage={setLanguage} setPage={setPage} announcement={announcement} onLogin={onLogin} />

      <div className="container mx-auto px-4 py-16">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 bg-blue-100 px-6 py-2 rounded-full mb-6">
            <Shield className="w-5 h-5 text-blue-600" />
            <span className={`text-blue-700 ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>{t.pageTitle}</span>
          </div>
          <h1 className={`text-gray-900 mb-4 ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>{t.subtitle}</h1>
          <p className={`text-gray-600 text-lg max-w-2xl mx-auto ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>
            {t.description}
          </p>
          <p className={`text-sm text-gray-500 mt-4 ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>
            {t.lastUpdated}
          </p>
        </div>

        {/* Introduction */}
        <Card className="p-8 mb-12 max-w-4xl mx-auto bg-gradient-to-r from-blue-50 to-cyan-50 border-2 border-blue-200">
          <p className={`text-gray-700 leading-relaxed ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>
            {t.introText}
          </p>
        </Card>

        {/* Sections */}
        <div className="max-w-4xl mx-auto space-y-8">
          {sections.map((section, index) => (
            <Card key={index} className="p-8 hover:shadow-lg transition-shadow">
              <div className="flex items-start gap-4 mb-4">
                <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-xl flex items-center justify-center flex-shrink-0">
                  <section.icon className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h2 className={`text-2xl text-gray-900 mb-4 ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>{section.title}</h2>
                </div>
              </div>
              <div className="pl-16">
                {section.content.map((item, idx) => (
                  <p key={idx} className={`text-gray-700 leading-relaxed mb-2 ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>
                    {item}
                  </p>
                ))}
              </div>
            </Card>
          ))}
        </div>

        {/* Contact Section */}
        <Card className="mt-16 p-8 bg-gradient-to-r from-blue-500 to-cyan-500 text-white max-w-4xl mx-auto">
          <div className="text-center">
            <Shield className="w-12 h-12 mx-auto mb-4 opacity-90" />
            <h2 className={`text-white mb-3 ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>{t.contactTitle}</h2>
            <p className={`text-blue-100 mb-6 ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>
              {t.contactText}
            </p>
            <div className={`space-y-2 text-blue-100 ${language === 'bn' ? 'font-[Noto_Serif_Bengali]' : ''}`}>
              <p>{t.contactEmail}</p>
              <p>{t.contactSupport}</p>
              <p>{t.contactPhone}</p>
              <p>{t.contactHotline}</p>
              <p>{t.contactAddress}</p>
            </div>
          </div>
        </Card>
      </div>

      <Footer language={language} setPage={setPage} />
    </div>
  );
}
